### ISSUE TITLE
Purchasing and manufacturing proposal

### ISSUE THREAD

**Issue by openvmp** [partcad/partcad#17]
Propose a convention/syntax to annotate the part declaration with sufficient data to order (SKU, API to order programatically) or to manufacture (what tools, materials are needed, url to instructions).

Ideally “pc order {-a} [part] {package}” should be able to purchase all parts, should they supply all the necessary data.

Load all this data into the Part object to enable search criteria (has ordering info, needs materials I have, etc). The implementation of search is outside of the scope of this issue.

**Comment by openvmp** [comment]
For patented parts, make it simple to mark parts so that it's intuitive that they must be purchased from the original manufacturer only.
Something like
```
part:
  mounting_bracket:
    vendor: <vendor>
    sku: <sku>
    manufacture:
      forbidden: True
      ...
vendor:
  <vendor>:
    url: ...${sku}...
    ordering:
      ...
```
